version: "3.4"
services:
        db:
                image: mariadb
                container_name: db
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: "1234"
                        MYSQL_DATABASE: "kanban"
        adminer:
                image: adminer
                container_name: adminer
                depends_on:
                        - db
                ports:
                        - "8082:8080"
        kanban_apache:
                build:
                        context: ./server
                        target: server
                image: kanban_apache
                container_name: kanban_apache
                restart: always
                volumes:
                        - ./server:/project
                        - /project/vendor
                ports:
                        - "8081:80"
                depends_on:
                        - db
        kanban_vue:
                build:
                        context: ./client
                        target: debug
                image: kanban_vue
                container_name: kanban_vue
                volumes:
                        - ./client:/project
                        - /project/node_modules
                ports:
                        - "8080:8080"
