version: "3"
services:
        db:
                image: mariadb
                container_name: db
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: "1234"
                        MYSQL_DATABASE: "kanban"
        adminer:
                image: adminer
                container_name: adminer
                restart: always
                depends_on:
                        - db
                ports:
                        - "8082:8080"
        composer:
                image: composer
                container_name: composer
                command: composer install
                volumes:
                        - ./server:/app
        kanban_apache:
                build: ./server
                container_name: kanban_apache
                volumes:
                        - ./server:/project
                ports:
                        - "8081:80"
                depends_on:
                        - composer
                        - db
                        - kanban_apache_migrate
        kanban_apache_migrate:
                build: ./server
                volumes:
                        - ./server:/project
                depends_on:
                        - db
                restart: on-failure
                command: php artisan migrate
        kanban_vue:
                build: ./client
                container_name: kanban_vue
                volumes:
                        - ./client:/project
                ports:
                        - "8080:8080"
                logging:
                        driver: none
