version: "3.4"
services:
        sqlite3:
                image: sstc/sqlite3
                container_name: sqlite3
                volumes:
                        - sqlite_db:/data
                tty: true
        kanban_apache:
                build:
                        context: ./server
                        target: server
                image: kanban_apache
                container_name: kanban_apache
                volumes:
                        - ./server:/project
                        - /project/vendor
                        - sqlite_db:/project/sqlite/
                ports:
                        - "8081:80"
        kanban_vue:
                build:
                        context: ./client
                        target: debug
                image: kanban_vue
                container_name: kanban_vue
                volumes:
                        - ./client:/project
                        - /project/node_modules
                ports:
                        - "8080:8080"
                logging:
                        driver: none
volumes:
        sqlite_db:
