version: "3.4"
services:
        kanban_apache:
                build:
                        context: ./server
                        target: server_prod
                image: kanban_apache_prod
                container_name: kanban_apache
                restart: always
                volumes:
                        - sqlite_db:/project/sqlite/
                        - /project
        kanban_vue:
                build:
                        context: ./client
                        target: prod
                image: kanban_vue_prod
                restart: always
                container_name: kanban_vue
                depends_on:
                        - kanban_apache
                ports:
                        - "80:80"
volumes:
        sqlite_db:
